<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    <style>
        body {
            font-family: DejaVu Sans;
            font-size: 10px;
        }

        h1 {
            text-align: center;
            margin-bottom: 0;
        }

        h3 {
            text-align: center;
            margin-top: 2px;
            font-weight: normal;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
        }

        th {
            background: #e5e5e5;
        }

        .footer {
            margin-top: 15px;
            font-size: 9px;
        }
    </style>

</head>

<body>

    <h1>SRE SYSTEM REPORT</h1>
    <h3>GSM Networks Monitoring Database</h3>

    <p><strong>Generated By:</strong> {{ auth()->user()->name }}</p>
    <p><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</p>

    @if(request('search'))
    <p><strong>Search:</strong> {{ request('search') }}</p>
    @endif

    @if(request('threat'))
    <p><strong>Threat:</strong> {{ request('threat') }}</p>
    @endif

    @if(request('date'))
    <p><strong>Date:</strong> {{ request('date') }}</p>
    @endif

    <table>

        <thead>

            <tr>
                <th>Date / Time</th>
                <th>Code Name</th>
                <th>Selector</th>
                <th>IMEI</th>
                <th>IMSI</th>
                <th>LAC</th>
                <th>CID</th>
                <th>BTS</th>
                <th>Threat</th>
            </tr>

        </thead>

        <tbody>

            @foreach($events as $event)

            <tr>

                <td>
                    {{ optional($event->observed_at)->format('M d, Y H:i') }}
                </td>

                <td>{{ $event->code_name }}</td>

                <td>{{ $event->selector->selector_value ?? '-' }}</td>

                <td>{{ $event->imei }}</td>

                <td>{{ $event->imsi }}</td>

                <td>{{ $event->lac }}</td>

                <td>{{ $event->cid }}</td>

                <td>{{ $event->bts_location }}</td>

                <td>{{ $event->threat_group }}</td>

            </tr>

            @endforeach

        </tbody>

    </table>

</body>

</html>